### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by Davicitoo** [SimCMinMax/AutoSimC#17]
Hi, when I try to run the script I get an error and the cmd.ex closes instantly. When  open the log.txt I get this message report:

2017-12-08 12:12:41,397 INFO Analyzer-file found at 'C:\AutoSimC-master\profiles\Analysis.json'.
2017-12-08 12:12:41,398 ERROR Error: 'utf-8' codec can't decode byte 0xe4 in position 20: invalid continuation byte
Traceback (most recent call last):
File "main.py", line 1421, in <module>
main()
File "main.py", line 1376, in main
player_profile = build_profile(args)
File "main.py", line 701, in build_profile
config.read_file(f)
File "D:\Python\Python36-32\lib\configparser.py", line 718, in read_file
self._read(f, source)
File "D:\Python\Python36-32\lib\configparser.py", line 1015, in _read
for lineno, line in enumerate(fp, start=1):
File "D:\Python\Python36-32\lib\codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 20: invalid continuation byte

Would be great if I get help enough to solve the problem. Thanks beforehand!

**Comment by scamille** [comment]
I just added extended error message for this in 94e941bf132912137a72f6556698f2ea91caa3da since this seems to be a common problem ;)

```
AutoSimC could not decode your input file '{file}' with encoding 'utf-8'.
Please make sure that your text editor encodes the file as 'utf-8',
or as a quick fix remove any special characters from your character name.
```

What this error means is that when you edited your input.txt file
1) You probably added some special characters somewhere, likely in your character name.
2) Your Text Editor saved the file with an encoding different than UTF-8, which we expect the input.txt file to be in.

So you either need to tell your Text Editor to save the file with the expected UTF-8 encoding, or as a quick-and dirty fix, you can also just remove any special (non-ASCII) characters. Please note that AutoSimC does not use your character name anyway, so you can just write eg.
priest=foo

**Comment by Davicitoo** [comment]
Thanks, that solved  my problem. It was all about my character name, whic is Eleyrä. Y removed the mas ä and all worked fine. Thanks :D
